### ISSUE TITLE
Allow additional service accounts to publish or consume from a Pub/Sub account

### ISSUE THREAD

**Issue by wfaler** [xlrte/core#5]
Many third party providers allow integration via Pub/Sub, we should make it possible to define additional accounts that can interact with pub/sub topics.

This should be on a per-environment basis, in the `resources.yaml`. We could add additional config to the pub-sub topic, such as:
```yaml
- name: the_topic
   additional_accessors:
   - account: serviceAccount:someaccount@…
      access: read|write|readwrite
```
